### ISSUE TITLE
Script says there is a new config version even though the config was just created

### ISSUE THREAD

**Issue by peioe** [sirjaren/redoflacs#5]
I get this:
 * There is a newer configuration file available!

 * It is recommended you generate a new configuration
 * file for use with this program.

 * To generate a new configuration file, run:
 * redoflacs --new-config

 * The above command will _NOT_ overwrite your
 * current configuration file.

 * Waiting 10 seconds before starting program...
 * Ctrl+C (Control-C) to abort...
 * Starting in: 10 9 

config file was just created by the script that I got from the repo.

**Comment by sirjaren** [comment]
@peioe,

Thanks for the report.
This is fixed in 5be5eb8d559e5fc6987fe07ebb347c4abce8a257.

Please re-download and let me know if things work for you.

**Comment by peioe** [comment]
Looks like it's fixed :) Thanks.
